# Generated by Django 4.1.4 on 2023-03-04 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordModels',
            fields=[
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='profiles.profile', verbose_name='UID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouveaux ticket de récupérations'), ('USED', 'Ticket utilisée')], default='NEW', max_length=30)),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetWorkModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text="The object's creation date/time", null=True, verbose_name='created on')),
                ('updated_on', models.DateTimeField(auto_now_add=True, help_text="The object's last update date/time", null=True, verbose_name='updated on')),
                ('url', models.CharField(default='', max_length=250)),
                ('key', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'Tiktok'), ('youtube', 'Youtube'), ('linkedin', 'Linkedin'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], default='', max_length=50)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
            options={
                'ordering': ['-updated_on'],
                'get_latest_by': 'updated_on',
                'abstract': False,
            },
        ),
    ]
