# Generated by Django 4.2 on 2023-10-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('de', 'Deutsch'), ('it', 'Italiano'), ('pt', 'Português'), ('ru', 'Русский'), ('zh', '中文'), ('ja', '日本語'), ('ar', 'العربية'), ('ko', '한국어'), ('hi', 'हिन्दी')], default='en', max_length=10),
        ),
    ]
