# Generated by Django 4.2 on 2023-10-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.CharField(choices=[('root', 'Admin'), ('player', 'Player')], default='player', max_length=20),
        ),
    ]
