# Generated by Django 4.2 on 2023-10-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_breaktimemodels_settings_forgetpassword_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breaktimemodels',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='forgetpassword',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='networkmodels',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='resetpasswordmodels',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='verifyidentifier',
            name='settings',
        ),
    ]
