# Generated by Django 4.2 on 2023-10-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.JSONField(default={}),
        ),
    ]
