# Generated by Django 4.2 on 2023-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isbotnet',
            field=models.BooleanField(default=False),
        ),
    ]
